version: "3.3"


### En volumenes de mysql ocupa el archivo init.sql el cual esta en la
### carpeta db al inicio del proyecto, para crear las tablas correspondientes

services:
    mysql:
        container_name: mysql
        restart: always
        expose:
            - 3306
        image: mysql:8.0.21
        volumes: 
          #- db_data:/var/lib/mysql
          - ./db:/docker-entrypoint-initdb.d/:ro
          #- ./db:/docker-entrypoint-initdb.d/init.sql
        environment:
          MYSQL_ROOT_PASSWORD: informatica110997
          MYSQL_DATABASE: knights
          MYSQL_USER: UserBDAT
          MYSQL_ROOT_HOST: 0.0.0.0
          MYSQL_PASSWORD: informatica110997
        networks:
            - red_privada

    backend:
        depends_on:
            - mysql
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        restart: always
        expose: 
            - 80
        networks:
            - red-proxy
            - red_privada
        environment: 
            VIRTUAL_HOST: localhost

    frontend:
        depends_on:
          - mysql
          - backend
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        container_name: frontend-react
        stdin_open: true
        networks: 
            - red-proxy
        environment: 
            VIRTUAL_HOST: localhost2

   
networks: 
    red-proxy:
        external: 
            name: nginx-proxy
    red_privada:
        
volumes: 
    db_data: